In [1]:
import pandas as pd
allpixDF = pd.read_pickle('ALL_PIXELS_DF')
allpixDF.head()

0    1    2    3    4    5    6    7    8    9      ...       85109  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      ...         0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      ...         0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      ...         0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      ...         0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      ...         0.0   

   85110  85111  85112                                               Path  \
0    0.0    0.0    0.0  D:\PROGRAMMING_PROJS\FooDMachineLearning\compl...   
1    0.0    0.0    0.0  D:\PROGRAMMING_PROJS\FooDMachineLearning\compl...   
2    0.0    0.0    0.0  D:\PROGRAMMING_PROJS\FooDMachineLearning\compl...   
3    0.0    0.0    0.0  D:\PROGRAMMING_PROJS\FooDMachineLearning\compl...   
4    0.0    0.0    0.0  D:\PROGRAMMING_PROJS\FooDMachineLearning\compl...   

   Orginal_Image_Size  Orginal_Image_Height  Orginal_Image_Width  \
0             22400.0                 112.0                200.0   
1             30000.0                 150.0                200.0   
2             30000.0                 150.0                200.0   
3             30000.0                 150.0                200.0   
4             30000.0                 150.0                200.0   

   Orginal_Image_Ratio  Product_Name  
0             1.785714         APPLE  
1             1.333333         BREAD  
2             1.333333         BREAD  
3             1.333333         BREAD  
4             1.333333         BREAD  

[5 rows x 85119 columns]

In [2]:
allpixDF.shape

(6141, 85119)

## Preparing dataset for ML models

In [3]:
allpixDF.drop(columns = ['Path'], inplace = True, axis=1)
allpixDF.head()
allpixDF.shape

(6141, 85118)

In [4]:
allpixDF = allpixDF.fillna(0)
allpixDF.shape

(6141, 85118)

We want to teach models to assign proper "Product_Name" label to images:

In [5]:
y_str = allpixDF['Product_Name']
ycc = pd.Categorical(y_str)
y = ycc.codes
X = allpixDF.drop(columns = ['Product_Name'], axis=1)
X.head()

0    1    2    3    4    5    6    7    8    9         ...           \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0         ...            
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0         ...            
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0         ...            
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0         ...            
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0         ...            

   85107  85108  85109  85110  85111  85112  Orginal_Image_Size  \
0    0.0    0.0    0.0    0.0    0.0    0.0             22400.0   
1    0.0    0.0    0.0    0.0    0.0    0.0             30000.0   
2    0.0    0.0    0.0    0.0    0.0    0.0             30000.0   
3    0.0    0.0    0.0    0.0    0.0    0.0             30000.0   
4    0.0    0.0    0.0    0.0    0.0    0.0             30000.0   

   Orginal_Image_Height  Orginal_Image_Width  Orginal_Image_Ratio  
0                 112.0                200.0             1.785714  
1                 150.0                200.0             1.333333  
2                 150.0                200.0             1.333333  
3                 150.0                200.0             1.333333  
4                 150.0                200.0             1.333333  

[5 rows x 85117 columns]

In [6]:
#X = X.dropna()
#X.shape

In [7]:
#X = X.fillna(0)

It's time to split dataset into training and testing datasets. From now on testing dataset is off limits, until models will be designed:

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,
                                                    random_state = 666)#because hail satan

In [9]:
print("X train shape: ", X_train.shape)
print("y train shape: ", y_train.shape)
print("======================")
print("X test shape: ", X_test.shape)
print("y test shape: ", y_test.shape)

X train shape:  (4912, 85117)
y train shape:  (4912,)
X test shape:  (1229, 85117)
y test shape:  (1229,)


## Filtering variables
A lot of columns in current dataset have low variance. There is no reason to include them in further analysis, as they do not provide any useful information. We'll fliter them out.

In [15]:
X_train.isnull().sum()

0                       0
1                       0
2                       0
3                       0
4                       0
5                       0
6                       0
7                       0
8                       0
9                       0
10                      0
11                      0
12                      0
13                      0
14                      0
15                      0
16                      0
17                      0
18                      0
19                      0
20                      0
21                      0
22                      0
23                      0
24                      0
25                      0
26                      0
27                      0
28                      0
29                      0
                       ..
85087                   0
85088                   0
85089                   0
85090                   0
85091                   0
85092                   0
85093                   0
85094       

In [9]:
X_train.iloc[:,0]

4786    0.0
3892    0.0
4023    0.0
5248    0.0
5147    0.0
1382    0.0
4674    0.0
1184    0.0
4777    0.0
1070    0.0
348     0.0
210     0.0
5351    0.0
4006    0.0
4921    0.0
1789    0.0
1529    0.0
2168    0.0
1268    0.0
2607    0.0
73      0.0
1281    0.0
1060    0.0
1201    0.0
5501    0.0
5936    0.0
2492    0.0
2826    0.0
626     0.0
1887    0.0
       ... 
676     0.0
5552    0.0
624     0.0
4120    0.0
1163    0.0
2324    0.0
885     0.0
2189    0.0
4047    0.0
204     0.0
3141    0.0
807     0.0
4584    0.0
3118    0.0
2448    0.0
575     0.0
2785    0.0
2830    0.0
2204    0.0
5180    0.0
563     0.0
222     0.0
1115    0.0
1469    0.0
2462    0.0
1993    0.0
70      0.0
2878    0.0
1950    0.0
1922    0.0
Name: 0, Length: 4912, dtype: float64

In [10]:
for c in range(X_train.shape[1]):
    if X_train.iloc[:,c].std() < 10:
        X_train=X_train.drop(X_train.columns[c])
X_train.shape

MemoryError: 

In [17]:
from sklearn.pipeline import make_pipeline
from sklearn.feature_selection import SelectFromModel
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import scale
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectKBest, mutual_info_classif

C:\Users\AdamT\Anaconda3\envs\foodmlenv\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [11]:
from sklearn.feature_selection import RFE, RFECV
pipeline = make_pipeline(RFE(RandomForestClassifier(100),1000,step=5000, verbose=1),
                          SVC())
cross_val_score(pipeline,X_train,y_train,cv=10).mean()

C:\Users\AdamT\Anaconda3\envs\foodmlenv\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


MemoryError: 

In [13]:
from sklearn.feature_selection import VarianceThreshold
sel = VarianceThreshold()

selmod = sel.fit(X_train)
selmod.transform(X_train)
X_train.shape

TypeError: unhashable type: 'slice'

In [10]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA, IncrementalPCA

In [38]:
scl = StandardScaler(copy=False)
scalmodel = scl.partial_fit(X_train)
X_train2 = scalmodel.transform(X_train)

In [39]:
ipca = IncrementalPCA(n_components=15000,whiten=True,batch_size=15000)
pcamodel = ipca.fit(X_train2)
X_traint_t = pcamodel.transform(X_train2)
X_traint_t.shape

C:\Users\AdamT\Anaconda3\envs\foodmlenv\lib\site-packages\sklearn\decomposition\incremental_pca.py:271: RuntimeWarning: Mean of empty slice.
  explained_variance[self.n_components_:].mean()
C:\Users\AdamT\Anaconda3\envs\foodmlenv\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


(4912, 4912)

In [40]:
X_traint_t

array([[  0.15295755,  -1.7896937 ,  -0.47675539, ...,  -6.90510751,
         -3.13489331, -10.30415312],
       [  0.42242515,  -1.02887073,   0.56934784, ..., -10.18278555,
         -6.8130618 ,   0.40288469],
       [  1.76046576,   0.8054803 ,   0.37513463, ..., -31.96626454,
        -18.89884141,   7.53785685],
       ...,
       [  0.35186315,   0.15104874,   0.67362598, ...,  -5.8769379 ,
         -3.85322901,   0.04787173],
       [  1.51407957,   0.41942717,   0.2530007 , ..., -27.02734224,
        -17.57469971,   0.62958396],
       [ -0.72873662,  -0.44473308,   2.87971568, ...,  13.99282038,
          8.12730531,  -0.37002408]])

In [22]:
pipeline = make_pipeline(SelectKBest(mutual_info_classif,100),
                          LogisticRegression())

scs1 = cross_val_score(pipeline,scale(X_traint_t),y_train,cv=5,verbose=1,n_jobs=-1)
print(scs1.mean())
scs1

C:\Users\AdamT\Anaconda3\envs\foodmlenv\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


0.3117847719393107


[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:  9.8min finished


array([0.30227948, 0.3001007 , 0.32721713, 0.31551901, 0.31380753])

In [21]:

pipeline = make_pipeline(SelectFromModel(RandomForestClassifier(200),threshold=0.003),
                          RandomForestClassifier())

scs = cross_val_score(pipeline,scale(X_traint_t),y_train,cv=4,verbose=1,n_jobs=-1)
print(scs.mean())
scs

C:\Users\AdamT\Anaconda3\envs\foodmlenv\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=4.
  % (min_groups, self.n_splits)), Warning)
[Parallel(n_jobs=-1)]: Done   2 out of   4 | elapsed:  1.4min remaining:  1.4min


0.43350927012353285


[Parallel(n_jobs=-1)]: Done   4 out of   4 | elapsed:  1.4min finished


array([0.42777334, 0.42348178, 0.44626743, 0.43651452])

In [23]:
scs_noselect = cross_val_score(RandomForestClassifier(),scale(X_traint_t),y_train,cv=4,verbose=1,n_jobs=-1)
print(scs_noselect.mean())
scs_noselect

C:\Users\AdamT\Anaconda3\envs\foodmlenv\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=4.
  % (min_groups, self.n_splits)), Warning)
[Parallel(n_jobs=-1)]: Done   2 out of   4 | elapsed:    6.3s remaining:    6.3s


0.2858747941796064


[Parallel(n_jobs=-1)]: Done   4 out of   4 | elapsed:    6.8s finished


array([0.28970471, 0.26963563, 0.29204266, 0.29211618])

In [24]:
from sklearn.neural_network import MLPClassifier
scs_nn = cross_val_score(MLPClassifier(),scale(X_traint_t),y_train,cv=4,verbose=1,n_jobs=-1)
print(scs_nn.mean())
scs_nn

C:\Users\AdamT\Anaconda3\envs\foodmlenv\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=4.
  % (min_groups, self.n_splits)), Warning)
[Parallel(n_jobs=-1)]: Done   2 out of   4 | elapsed:   47.5s remaining:   47.5s


0.31789417764835315


[Parallel(n_jobs=-1)]: Done   4 out of   4 | elapsed:   52.2s finished


array([0.30646449, 0.31983806, 0.31747334, 0.32780083])

In [35]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
import numpy as np

mlpc = MLPClassifier(hidden_layer_sizes=(500, 500,500,500,500),solver = 'sgd',verbose=True, batch_size =1000)
mlpcmodel = mlpc.partial_fit(X_train,y_train,classes=np.unique(y))
ypred = mlpcmodel.predict(X_train)
ytpred = mlpcmodel.predict(X_test)
print(accuracy_score(y_train,ypred))
print(accuracy_score(y_test,ytpred))

#scs_nnb = cross_val_score(MLPClassifier(hidden_layer_sizes=(100, 50, 50)),scale(X_train),y_train,cv=4,verbose=1,n_jobs=-1)
#print(scs_nnb.mean())
#scs_nnb

C:\Users\AdamT\Anaconda3\envs\foodmlenv\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:927: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if np.setdiff1d(classes, self.classes_, assume_unique=True):


Iteration 1, loss = 4.02640041
0.19157166123778502
0.2050447518307567


In [42]:
pipeline = make_pipeline(SelectFromModel(RandomForestClassifier(300),threshold=0.003),
                          RandomForestClassifier(n_estimators=100,n_jobs=-1,verbose=1))

scs = cross_val_score(pipeline,scale(X_traint_t),y_train,cv=10,verbose=1,n_jobs=-1)
print(scs.mean())
scs

C:\Users\AdamT\Anaconda3\envs\foodmlenv\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


0.4429946376492576


[Parallel(n_jobs=-1)]: Done  10 out of  10 | elapsed:  8.2min finished


array([0.45229008, 0.4148728 , 0.44422311, 0.44176707, 0.45807771,
       0.4742268 , 0.45228216, 0.41127349, 0.45052632, 0.43040685])

In [43]:
from sklearn.decomposition import NMF, LatentDirichletAllocation
lda = LatentDirichletAllocation(n_components=10000, max_iter=10,
                                learning_method='online', batch_size = 2000,
                                learning_offset=50., n_jobs = -1,
                                random_state=0)
ldamodel = lda.partial_fit(X_train2)
X_traint_t2 = ldamodel.transform(X_train2)
X_traint_t2.shape

ValueError: Negative values in data passed to LatentDirichletAllocation.partial_fit

## Adding some meta information
Basing on pixels' values we'll add few columns containing some general infrmation about colors in pictures.
We'll run kmeans (3 centroids) clustering for each row (separately for R, G and B). We expect to gain 9 values (centroids) for each row, which will provide some insight into most characteristic pixel values for every image.